# Clippy configuration for enhanced linting

# Performance lints
warn-on-all-wildcard-imports = true

# Complexity limits
cognitive-complexity-threshold = 30
type-complexity-threshold = 250

# Style preferences
single-char-binding-names-threshold = 5
trivial-copy-size-limit = 128
too-many-arguments-threshold = 9

# Allow certain patterns that are common in financial data processing
allow-expect-in-tests = true
allow-unwrap-in-tests = true

# Suppress overly pedantic lints for this domain
msrv = "1.84.0"  # Minimum supported Rust version