# Configuration for cargo-deny to check dependencies

[licenses]
allow = [
    "MIT",
    "Apache-2.0", 
    "Apache-2.0 WITH LLVM-exception",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "CC0-1.0",
    "Unicode-3.0",
    "Zlib",
]
confidence-threshold = 0.95

[bans]
multiple-versions = "allow"
wildcards = "deny"

[advisories]
db-urls = ["https://github.com/rustsec/advisory-db"]
unmaintained = "workspace"
yanked = "deny"

[sources]
# Only allow crates from crates.io and git
unknown-registry = "deny"
unknown-git = "deny"
allow-git = []